server:
  port: 10000
spring:
  application:
    name: aladdin-admin-server
  output:
    ansi:
      enabled: ALWAYS
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.163.com
    username: xiongyayun428@163.com
    password: ENC(nXUdi3kEc7Yg1aap7Q4/l3s+Ah035P+Qtd0SxFBr9rp6JC4qYkRqXfSJIGW7BBis)
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  boot:
    admin:
      ui:
        title: "雅典娜应用监控管理"
        favicon: static/favicon.ico
        brand: "<img src='static/img/icon-spring-boot-admin.svg'><span>雅典娜应用监控管理</span>"
#      notify:
#        mail:
#          from: xiongyayun428@163.com
#          to: 531158453@qq.com
#          cc: xiongyayun428@163.com
#        dingtalk:
#          enabled: true
#          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=5f588ab27b1f7c1f0b2bd82cbe3ee609554141bbf51fad8f133ef2a747945c2f
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    #可以关闭指定的端点
    shutdown:
      enabled: false
jasypt:
  encryptor:
    password: xiongyayun428