server:
  port: 8761
spring:
  application:
    name: aladdin-eureka
  security:
    user:
      name: eureka
      password: eureka
#      roles:
#        - admin
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        url: http://localhost:10000
        username: admin
        password: admin
  cloud:
    zookeeper:
      connect-string: 192.168.1.1:2181
management:
  endpoints:
    web:
      exposure:
        include: "*"