server:
  port: 9000
spring:
  application:
    name: aladdin-gateway
  devtools:
    restart:
      enabled: false
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: admin
  cloud:
    gateway:
      # 全局超时
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          lower-case-service-id: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        - id: after_route
          uri: https://crm.prolinkwm.com
          predicates:
            # 匹配路径转发
            - Path=/auth/*
          metadata:
            connect-timeout: 500
            response-timeout: 500
        - id: host_route
          uri: http://baidu.com
          predicates:
            - Host=**.baidu.com
#        - id: rate_limit_route
#          uri: https://example.org
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
eureka:
  instance:
    # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 60
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90秒）超时将剔除服务
    lease-expiration-duration-in-seconds: 120
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/ #, http://admin:admin@47.107.179.245:8761/eureka/

  hystrix:
    command:
      fallbackcmd:
        execution:
          isolation:
            thread:
              # 超时时间，若不设置超时时间则有可能无法触发熔断
              timeoutInMilliseconds: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: debug