spring:
  application:
    name: aladdin-gateway
#eureka:
#  instance:
#    # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    prefer-ip-address: true
#    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认为30秒）
#    lease-renewal-interval-in-seconds: 60
#    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90秒）超时将剔除服务
#    lease-expiration-duration-in-seconds: 120
#  client:
#    service-url:
#      defaultZone: http://eureka:eureka@localhost:8761/eureka/ #, http://admin:admin@47.107.179.245:8761/eureka/

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            # 超时时间，若不设置超时时间则有可能无法触发熔断
#            timeoutInMilliseconds: 5000
